---
# tasks file for mysql
  - name: Cria o DB para o Wordpress
    mysql_db: name={{ wp_mysql_db }} state=present

  - name: Cria um usuario DB para o WordPress
    mysql_user:
     name={{ wp_mysql_user }}
     password={{ wp_mysql_password }}
     priv=*.*:ALL
